---
title: "🗓️ Introduction to Logic, Week 02"
---

In this first week, we will cover what you can expect to learn from this course and the course logistics: all you need to know about the structure of the lectures, classes, assessments, and how we will interact throughout this course.

| Unit | Topic | Pages |
|---|---|---|
|1 | What is deductive logic? | 1-8 |
|2 | Validity and soundness | 9-19 |
| 3 | Forms of inference | 20 |
| 4 | Proofs | 28 |

In this first week, we will cover what you can expect to learn from this course and the course logistics: all you need to know about the structure of the lectures, classes, assessments, and how we will interact throughout this course.

## 👨‍🏫 Lecture Slides

Either click on the slide area below or click [here](slides.qmd) to view it in fullscreen.
Use your keypad to navigate the slides.

<div class="container" style="position: relative;overflow: hidden;width: 100%;min-height:600px;">
<iframe src="slides.html" style="position=absolute;top: 0;left: 0;bottom: 0;right: 0;width: 100%;min-height:600px;"></iframe>
</div>

🎥 Looking for lecture recordings? You can only find those on Moodle.

## ✍️ Coursework

🚧 Come back after the lecture to read the coursework instructions for the week 🚧


## 📚 Recommended Reading

- Check the end of slides for the list of references cited in the lecture.

## 📟 Communication

- If you feel like it, introduce your 'selves' in the `#introductions` channel in [Discussions](https://stetson.instructure.com/courses/38093/discussion_topics/162462)
